name: 'Release Tag'
description: 'Exports either the release tag or branch name as release_tag'
inputs:
  output:
    description: 'Path to write release_tag to'
outputs:
  release_tag:
    description: 'Either the release tag or branch name'
   
runs:
  using: 'node12'
  main: 'packed/index.js'
