#!/usr/bin/env bash
#
# check_constants.sh - Detect removed #define macros and enum constants
# between the base and head public headers, via ctags name extraction.
#
# WHY THIS EXISTS: abicc's "changed_constants" field is #define-specific, so
# a removed constant declared via an anonymous enum (`enum { X = 20 };` --
# aws-c-common's own style for its length constants) produces zero signal on
# either report, even though referencing it by name is a real compile error.
# A named enum's removed member is caught separately under "Problems with
# Data Types", so this script is a narrow supplement for the anonymous-enum
# case specifically, not a general replacement for abicc's diffing.
#
# Method: ctags extracts macro ('d') and enumerator ('e') names directly from
# the header text (independent of DWARF/binary analysis, so it can't miss
# anything that never reaches a compiled symbol). Any name present in the
# base headers but absent from the head headers is a removed constant --
# any caller referencing it by name will fail to compile, unconditionally.
#
# Inputs (env):
#   ABI_BASE_INSTALL   install prefix of the base build (must contain include/)
#   ABI_HEAD_INSTALL   install prefix of the head build (must contain include/)
#
# Outputs (appended to $GITHUB_ENV):
#   ABI_REMOVED_CONSTANTS_COUNT  number of removed constant names (0 if none)
#   ABI_REMOVED_CONSTANTS_FILE   path to a file listing them, one per line
#                                (this pipeline's $GITHUB_ENV is re-sourced with
#                                plain `bash source`, not the real GitHub Actions
#                                runner's multi-line-heredoc-aware parser -- so,
#                                unlike the real GITHUB_ENV, it can only carry
#                                single-line KEY=value pairs; the actual names go
#                                in this file instead, same pattern as
#                                ABI_ACC_LOG/ABI_REPORT_HTML elsewhere in this
#                                pipeline)

set -uo pipefail

BASE_INSTALL="${ABI_BASE_INSTALL:?ABI_BASE_INSTALL must be set}"
HEAD_INSTALL="${ABI_HEAD_INSTALL:?ABI_HEAD_INSTALL must be set}"

extract_names() {
  # --kinds-C=+d+e: enable macro definitions (d) and enumerators (e) on top
  # of ctags' default kind set. Anonymous-enum autogenerated names
  # (__anon<hash>) are excluded -- they're not real symbols, and their hash
  # changes between builds even with no real change, which would make every
  # run "detect" a spurious removal+addition pair.
  ctags -R --kinds-C=+d+e -x "$1/include" 2>/dev/null \
    | awk '{print $1, $2}' \
    | grep -v '^__anon' \
    | grep -E ' (macro|enumerator)$' \
    | awk '{print $1}' \
    | sort -u
}

BASE_NAMES="$(mktemp)"
HEAD_NAMES="$(mktemp)"
extract_names "$BASE_INSTALL" > "$BASE_NAMES"
extract_names "$HEAD_INSTALL" > "$HEAD_NAMES"

REMOVED="$(comm -23 "$BASE_NAMES" "$HEAD_NAMES")"
rm -f "$BASE_NAMES" "$HEAD_NAMES"

REMOVED_FILE="$(mktemp)"
printf '%s\n' "$REMOVED" > "$REMOVED_FILE"
COUNT=0
if [[ -n "$REMOVED" ]]; then
  COUNT="$(printf '%s\n' "$REMOVED" | grep -c .)"
  echo "Removed constant(s) detected (present in base headers, absent from head):"
  printf '%s\n' "$REMOVED" | sed 's/^/  - /'
else
  echo "No removed macro/enum constants detected."
fi

{
  echo "ABI_REMOVED_CONSTANTS_COUNT=${COUNT}"
  echo "ABI_REMOVED_CONSTANTS_FILE=${REMOVED_FILE}"
} >> "$GITHUB_ENV"

exit 0
