name: CI

on: 
  push:
    paths:
      - 'builder.py'
      - '.github/workflows/ci.yml'
      - '.github/actions/**/*'

jobs:
  aws-c-common:
    runs-on: ubuntu-latest
    
    steps:
    - name: Build aws-c-common + consumers
      container:
        image: docker.pkg.github.com/awslabs/aws-crt-builder/aws-crt-ubuntu-16:x64
        env:
          BUILDER_ARGS: -p aws-c-common build linux-clang-9-linux-x64-downstream
