name: CI

on: 
  push:
    paths:
      - 'builder.py'
      - '.github/workflows/ci.yml'
      - '.github/actions/**/*'

jobs:
  aws-c-common:
    runs-on: 'ubuntu-latest'

    # We can't use the `uses: docker://image` version yet, GitHub lacks authentication for packages
    steps:
    - name: Build aws-c-common + consumers
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u awslabs --password-stdin
        docker pull docker.pkg.github.com/awslabs/aws-crt-builder/aws-crt-ubuntu-16:x64
        docker run -v $GITHUB_WORKSPACE /-w /workspace docker.pkg.github.com/awslabs/aws-crt-builder/aws-crt-ubuntu-16:x64 -p aws-c-common build linux-clang-9-linux-x64-downstream

