name: Dispatcher Workflow

permissions:
  contents: read
  actions: read
  id-token: write

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  decide:
    runs-on: ubuntu-latest
    outputs:
      trigger_create: ${{ steps.set_trigger.outputs.trigger_create }}
      trigger_sanity_test: ${{ steps.set_trigger.outputs.trigger_sanity_test }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set flags for create channel and sanity test
        id: set_trigger
        run: |
          # checks for previous successful runs on the branch
          echo "trigger_sanity_test=true" >> $GITHUB_OUTPUT
          BRANCH="${GITHUB_REF##*/}"
          COMMIT_ID=$(gh run list -w="Dispatcher Workflow" --branch="$BRANCH" --json conclusion,headSha --jq 'first(.[] | select(.conclusion == "success")) | .headSha // empty')
          if [[ -z "$COMMIT_ID" ]]; then
            echo "Found no successful dispatch runs on this branch."
            echo "trigger_create=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Found previous successful run for commit $COMMIT_ID"
          fi
          # check if new changes on push requires re-running the create-channel
          git fetch origin ${{ github.event.before }}
          CHANGED="$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
          echo "---------------------"
          echo "CHANGES"
          echo "---------------------"
          echo "$CHANGED"
          NEEDED_CHANGES="$(echo "$CHANGED" | grep -E '(^.github/actions/.*)|(^.github/workflows/[^/]*\.sh$)|(^.github/workflows/create-channel.yml$)|(^builder/.*)|(^.github/workflows/dispatcher.yml)')"
          echo "---------------------"
          echo "CHANGES FOR CREATE"
          echo "---------------------"
          echo "$NEEDED_CHANGES"
          if [ -n "$NEEDED_CHANGES" ]; then
            echo "trigger_create=true" >> $GITHUB_OUTPUT
          else
            echo "trigger_create=false" >> $GITHUB_OUTPUT
          fi
  run_create:
    needs: decide
    if: ${{ needs.decide.outputs.trigger_create == 'true' }}
    uses: ./.github/workflows/create-channel.yml
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      CRT_CI_ROLE_ARN: ${{ secrets.CRT_CI_ROLE_ARN }}
      AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}

  run_sanity_test:
    needs: [decide, run_create]
    if: ${{ needs.decide.outputs.trigger_sanity_test == 'true' && needs.decide.outputs.trigger_create == 'true' }}
    uses: ./.github/workflows/sanity-test.yml
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      CRT_CI_ROLE_ARN: ${{ secrets.CRT_CI_ROLE_ARN }}
      AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}

  run_sanity_test_only:
    needs: decide
    if: ${{ needs.decide.outputs.trigger_sanity_test == 'true' && needs.decide.outputs.trigger_create != 'true' }}
    uses: ./.github/workflows/sanity-test.yml
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      CRT_CI_ROLE_ARN: ${{ secrets.CRT_CI_ROLE_ARN }}
      AWS_ECR_REPO: ${{ secrets.AWS_ECR_REPO }}