name: Docker Base Images

on: 
  push:
    branches: 
      - '*'
      - '!master'
    paths:
      - '.github/docker-images/raspbian-armv6/base.Dockerfile'
      - '.github/workflows/docker-base-images.yml'
      - '.github/workflows/*.sh'

jobs:
  raspbian-armv6:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [v6]
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1
    
    - name: Build raspbian-arm${{ matrix.arch}} image
      run: ./.github/workflows/docker_buildx.sh \
        docker.pkg.github.com \
        awslabs \
        ${{ secrets.DOCKER_TOKEN }} \
        awslabs/aws-crt-builder/raspbian-arm${{ matrix.arch }} \
        latest \
        .github/docker-images/raspbian-arm${{ matrix.arch }} \
        --file=.github/docker-images/raspbian-arm${{ matrix.arch }}/base.Dockerfile \
        --compress=true --platform=linux/arm/${{ matrix.arch }} --target=base
