name: Lint

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  autopep8:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Build and Test
      run: |
        python3 -m pip install --upgrade setuptools
        python3 -m pip install --upgrade autopep8
        python3 -m autopep8 --exit-code --diff --recursive setup.py builder
