name: TEST

on: 
  push:
    paths:
      - '.github/docker-images/test/Dockerfile'
      - '.github/workflows/test.yml'

jobs:
  package:
    name: Package builder app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v1

      # re-enable this when requirements.txt has actual dependencies
      # - name: Bundle dependencies
      #   run: |
      #     python3 -m pip install -r requirements.txt --target builder
      #     rm -rf builder/*.dist-info

      - name: Package builder
        run: |
          mkdir -p build
          python3 -m zipapp --python="/usr/bin/env python3" --output=build/builder builder

      - name: Store builder
        uses: actions/upload-artifact@v1
        with:
          name: builder
          path: build/builder

  test-x64:

    runs-on: ubuntu-latest
    needs: package
    env:
      IMAGE_NAME: test
      IMAGE_TAG: x64

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: Fetch builder
      uses: actions/download-artifact@v1
      with:
        name: builder
        path: .github/docker-images/test-x64

    - run: cp .github/docker-images/entrypoint.sh .github/docker-images/test-x64/entrypoint.sh
    
    - name: Build test image
      uses: whoan/docker-build-with-cache-action@v3
      with:
        username: awslabs
        password: ${{ secrets.DOCKER_TOKEN }}
        image_name: awslabs/aws-crt-builder/aws-crt-test
        image_tag: x64
        registry: docker.pkg.github.com
        context: .github/docker-images/test-x64
        build_extra_args: "--compress=true"  
